### ISSUE TITLE
HD v2 Roadmap

### ISSUE THREAD

**Issue by lpenguin** [KranX/Vangers#249]
- [x] Add a resolution switch in the graphics options (#252)
- [x] Scaled rendering for Main menu and Escave, and widescreen rendering for Surface (#253)
- [x] Fix broker counselor questions (#369)
- [x] Responsive UI: 
  - [x] Add align left/right flags for Surface UI elements and `layout(...)` method (#255)
  - [x] Add align flags support into the script parser (#256)
  - ~~Add Bitmap UI widget (#254)~~
  - [x] Cut Surface UI frames (main and inventory) into 4 pieces, and render them separately
  - [x] Expand surface rendering to full-screen (#307)
  - [ ] Move pause menu to the center of the screen (#349)
- [x] Camera offset
  - [x] Offset camera for main/inventory interfaces (#308)
  - ~~Change 3d models positioning according to camera offset~~
  - [x] Change effects positioning according to camera offset (#311)
  - [x] Change drop mechanics according to camera offset (#312)
  - [x] Fix compass offsets (#309)
  - [x] Fix oxygen resource offset (#310)
  - [x] Fix camera zoom mode (#338)

**Comment by DiTolk** [comment]
Looks doable! 
Good luck, man!

**Comment by caiiiycuk** [comment]
@lpenguin можно закрывать последний чекбокс закрыли

**Comment by lpenguin** [comment]
@caiiiycuk отлично!
